### ISSUE TITLE
Fare girare sul cloud un'installazione dal branch di Alfredo

### ISSUE THREAD

**Issue by albertocottica** [spaghetti-open-data/tweetyourmep#74]
... così ci facciamo su un po' di prove. 

@seralf che non valga la pena che tu faccia una pull request?

**Comment by seralf** [comment]
ciao Alberto ti rispondo al volo, e dopo mi rileggo un po' di roba e mi allineo.

il branch aggiornato dovrebbe essere questo:
https://github.com/spaghetti-open-data/tweetyourmep/tree/dev-seralf
(spero di non aver fatto pasticci)

contiene qualche aggiustamento sintattico necessario per riprodurre l'applicazione in locale con express 4 (a me gira: ho fatto la prova rilanciandolo da zero), e qualche aggiustamento nei config

per l'importazione c'è uno script che acquisisce dall'XML (predisposto in caso in tempi brevi aggiungano loro stessi lì il resto: lo estendiamo e buttiamo via gli scraper)
in alternativa c'è un file di prova JSON con un bel po' di dati, in parte ripuliti, in parte da sistemare ancora un po'

Non ho avuto tempo di scrivere l'import da JSON statico su Mongo (e meno che mai dai CSV), ma dovrebbe essere veramente banale, tipo "leggi il documento ed inseriscilo se non c'è già", a meno di microscopiche modifiche nello schema se ci dovessero servire.

appena posso però faccio una directory dove possiamo salvare script/progetti per scraper e soprattutto l'ultima versione dei dati. Mi sta venendo la fortissima tentazione di rilasciare noi a loro una versione pubblicabile dei loro dat...i ;-)

**Comment by seralf** [comment]
TODO:
+ merge da dev-seralf a master delle modifiche APi per express 4, eventuali ulteriori miglioramenti e correzioni di bug
+ documentare i passi per riprodurre l'applicazione in locale (qualcosa c'è già nel README)
+ documentare eventuali passi per creazione con docker e/o vagrant, in modo da rendere tutta l'applicazione riproducibile

**Comment by albertocottica** [comment]
@seralf a che punto siamo? Io avrei bisogno di accesso a una versione da cui posso fare screenshots, configurarmi il tweet etc. Possiamo fare in due modi:

1. Fai tu un'installazione a cui io poi posso accedere via browser (però devo potere modificare `config.js`).
1. Ci mettiamo su Skype/Hangout e mi guidi mentre installo in locale sulla mia macchina, partendo dal repo. 

La seconda cosa ha il vantaggio che ho più informazioni quando scrivo la documentazione.

**Comment by seralf** [comment]
per ora abbiamo fatto merge sulla attuale master, quindi direi di chiudere (magari riapriamo all'occorrenza)
