### ISSUE TITLE
"Bitdeli Badge"? 

### ISSUE THREAD

**Issue by albertocottica** [spaghetti-open-data/tweetyourmep#78]
C'è una pull request un po' sospetta: #73 . @seralf , tu figuri come autore. Se davvero è tua, accettala, se no la rimbalziamo.

**Comment by seralf** [comment]
francamente non me lo ricordavo, ma credo fosse un componente per tracciare
analytics sui repository, probabilmente se ne era parlato durante i vari
brainstorming e poi la cosa è morta là

2017-01-08 18:25 GMT+01:00 Alberto Cottica <notifications@github.com>:
