### ISSUE TITLE
Scrivere il tweet anti copyright e precaricarlo sull'applicazione

### ISSUE THREAD

**Issue by albertocottica** [spaghetti-open-data/tweetyourmep#84]
Ora che @seralf ha ripristinato TWYMEP e aggiornato i suoi dati, entriamo nella fase in cui la trasformiamo in uno strumento per campagne di informazione e mobilitazione. 

Come prima fase, si tratta di inserire del testo nel tweet che viene generato quando l'utente ha scelto il MEP. Se non ricordo male (Alfredo, perdonami ma sono in vacanza e non me la sento di mettermi a smanettare per fare girare TWYMEP in locale) un po' di roba c'era già – anzi ci *deve* essere, perché ci deve essere `@mepname` perché la cosa funzioni. Si tratta quindi solo di fare un edit molto semplice. 

Alf, di questo posso occuparmi io se mi segnali qual è il file, nel codice, che precarica il tweet.

**Comment by seralf** [comment]
guarda Alberto non ho avuto tempo di provarlo davvero, ma se non ricordo
male non c'era una area dove generare un testo per campagne. Ricordo che se
ne era parlato ma non sono riuscito ad individuarla se c'è, credo la cosa
avesse a che fare con dei filtri di twitter atti ad evitare tweetbombing
diciamo così.

Intanto se vuoi potrei farti merge del dev sul master, se credi sia più
pratico, sennò basta che cloni il repo e poi fai checkout di dev-seralf...
una volta ottenuta una versione che riteniamo abbastanza stabile ne
facciamo merge. La cosa avrebbe senso soprattutto se paolo potesse rifare
deploy della nuova versione (Paolo ci leggi?) ma qui non ho capito se
ancora abbiamo un server o no.

Intanto sarebbe da capire cosa serve a Laura.

Io di mio sono a singhiozzo ma ogni tot posso spenderci qualche ora ;-)


Il giorno 16 gennaio 2017 07:08, Alberto Cottica <notifications@github.com>
ha scritto:

**Comment by albertocottica** [comment]
No, no, certo, non c'era. Però c'è un punto del codice in cui l'applicazione compone il tweet, che contiene perlomeno la menzione al MEP che si vuole contattare. Se non sbaglio ci avevamo messo anche un link alla pagina web dell'app (apps.spaghettiopendata.org/tweetyourmep), forse in forma di shortlink. 

In quel punto lì inseriamo il messaggio di campagna. Solo che non capisco dove stia quel punto... @paolomainardi , tu ti ricordi?

**Comment by jilt** [comment]
Vi ho persi, sulla mia macchina condivisa non ho neanche configurato mongo.
Se riusciamo a vederci e configurare la macchina insieme alfredo ci emtterei un'oretta a mettermi in pari, ci vuole solo la volonta' di farlo :)

**Comment by seralf** [comment]
ok! mi spaventa solo di bloccarti io, che sono a singhiozzo! io diciamo
potrei provare ad essere online in orari un po' tardivi, dopo le 19:00 sono
un po' più affidabile, è fattibile?

tu sei puoi intanto verificare se hai mongo e nodejs, il resto ci si mette
molto poco. Io stesso non mi ricordo diverse cose fatte sulle API, per ora
ho pensato solo a rimetterlo in piedi senza errori, conviene ragionarci su
nuovamente in base a ciò che potrebbe servire, magari ci da una mano Paolo
se/quando può (certamente si ricorda meglio di me).

Il giorno 23 gennaio 2017 09:47, Laura Camellini <notifications@github.com>
ha scritto:

**Comment by albertocottica** [comment]
Grandi. Se riuscite a farlo andare su un server a cui ho accesso, poi cerco di capire come scrivere il tweet precaricato... sempre che @paolomainardi o qualcun altro non mi indichino cosa cercare.

La mia tattica è di usare l'applicazione: vedere che cosa viene scritto nel tweet (mi ricordavo che ci fosse uno shortlink, o qualcosa così), poi cercare quella stessa stringa nel repo. A quel punto basterà sostituire la stringa precaricata che c'è ora con quella che tratta della riforma sul copyright.

**Comment by seralf** [comment]
se lo faccio io devo guardarci Alberto (per evitare di incollare
brutalmente un testo che al prossimo giro dobbiamo ricambiare a manina),
quindi porta pazienza :-)

Il giorno 24 gennaio 2017 14:48, Alberto Cottica <notifications@github.com>
ha scritto:

**Comment by albertocottica** [comment]
@seralf secondo me non è male anche cambiare a mano, purché la cosa sia documentata. Se capisco qual è la linea del codice incriminata, poi metto su una pagina del wiki in cui spiego come si fa a usare TWYMEP per una campagna.

**Comment by seralf** [comment]
ok ci do una occhiata stasera da casa

Il giorno 27 gennaio 2017 08:38, Alberto Cottica <notifications@github.com>
ha scritto:

**Comment by albertocottica** [comment]
Closed.
