### ISSUE TITLE
Aggiornare il wiki per la versione "Campaign ready"

### ISSUE THREAD

**Issue by albertocottica** [spaghetti-open-data/tweetyourmep#86]

**Comment by albertocottica** [comment]
Per ora le istruzioni sull'installazione sono nel vecchio README. Sono ancora valide? @seralf

**Comment by seralf** [comment]
ho fatto merge degli sviluppi da development al master, quindi il README
che vedi descrive le istruzioni attuali. Se ci sono errori / omissioni etc
segnalatemeli.
Anzi mò aggiungo una issue per una macchinetta vagrant: se rendiamo
facilmente replicabile tutto l'ambiente credo sia più facile anche
migliorare, aggiornare etc

2017-02-26 14:22 GMT+01:00 Alberto Cottica <notifications@github.com>:

**Comment by albertocottica** [comment]
Closing.
