### ISSUE TITLE
Aggiornare i dati con il parlamento in carica (!)

### ISSUE THREAD

**Issue by albertocottica** [spaghetti-open-data/tweetyourmep#88]
@seralf scusa se ti stresso ma mi sono accorto che il database non è aggiornato. MEPS.json contiene i MEP della scorsa legislatura!

**Comment by albertocottica** [comment]
C'è uno scraper fatto da Guglielmo qui: https://morph.io/openpolis/meps

Però i dati sono scaricabili solo come CSV o SQLite.

**Comment by seralf** [comment]
ho usato uno scraper mio scritto in scala, non gli altri, che pensavo comunque di citare così che al prossimo giro se qualcuno volesse usare altre modalità di reload possa farlo.
Ecco perché pure l'output del mio mio l'ho salvato statico qui:
https://github.com/spaghetti-open-data/tweetyourmep/blob/master/input/MEPS.json
(questi sono aggiornati alla versione attuale)
L'import dal json statico facilita anche la replica, nel caso non ci sia rete, sganciamo insomma lo scraping dal resto.
A breve pubblico anche lo scraper scala, non riesco a trovare il tempo di rimetterlo un secondo in ordine

**Comment by albertocottica** [comment]
Hai ragione tu: il comando `node input-meps-json.js` rimanda al file input-meps-json.js che contiene una variabile `mep_file = config.input_json ;`. Nel config.js.development la variabile è configurata correttamente: `input_json: "../input/MEPS.json",`

Solo che, quando lancio l'app, io vedo Amelia Andersdotter (non rieletta nel 2014) e non Julia Reda (eletta per la prima volta nel 2014). Hai idea del perché succeda?

**Comment by seralf** [comment]
uhm da me sembra girare bene, tant'è che anche nel file di input i dati sono giusti:
https://github.com/spaghetti-open-data/tweetyourmep/blob/master/input/MEPS.json

non è che per qualche motivo stai usando una vecchia versione del db?
prova a re-importare dal JSON
